### ISSUE TITLE
Can not package SWC for Mobile Platform

### ISSUE THREAD

**Issue by aruis** [GradleFx/GradleFx#183]
I want package swc file use from mobile platform. 
But,I do not know how.
I can only use type='swc' or type='mobile',this looks has problem.

for example ,I want package 'https://code.google.com/p/stagewebviewbridge/' with gradlefx.

**Comment by SlevinBE** [comment]
If you want to create a library for use in a mobile project, you should either use 'swc' or 'swcAir' as the project type. These will package your project into a swc file. You can manually specify all mobile specific dependencies which you require.
Is there a specific problem you're facing?

**Comment by aruis** [comment]
Thank you. 
Now the situation is，I want package a library used for air project. and use type='swcAir', but build failure. error log show:cannot find class flash.filesystem.File .

**Comment by SlevinBE** [comment]
Have you specified the AIR SDK as a dependency?

**Comment by aruis** [comment]
Do you mean specified flexHome like this?

subprojects {
    apply plugin: 'gradlefx'
    flexHome = '/Users/liurui/develop/sdk/flex/4.14.1'
    srcDirs = ['src']
}

**Comment by SlevinBE** [comment]
indeed, like that, or by specifying the SDK as a dependency as described here: http://doc.gradlefx.org/en/latest/sdk_auto_install.html

**Comment by aruis** [comment]
I try use sdk auto install,like this:
type = 'swcAir'
repositories {
    ivy {
        name 'Apache'
        artifactPattern 'http://apache.cu.be/flex/[revision]/binaries/[module]-[revision]-bin.[ext]'
    }

}
dependencies {
    flexSDK group: 'org.apache', name: 'apache-flex-sdk', version: '4.14.1', ext: 'tar.gz'
    airSDK files('/Users/liurui/develop/sdk/flex/AdobeAIRSDK.tbz2')
}
but error log show:

  Apache Flex compc (Component Compiler)
  Version 4.14.1 build 20150325
  Copyright 2015 The Apache Software Foundation.
  /Users/liurui/.gradle/gradleFx/sdks/ebca91370fb119f48e5867aa9b6ade0ce98949a5/frameworks/flex-config.xml(65): ERROR:cannot open“libs/player/16.0/playerglobal.swc”
  
        </external-library-path>

**Comment by SlevinBE** [comment]
Reason for this issue is that GradleFx only downloads the 11.1 version of playerglobal, and the AIR SDK only provides the 17.0 version of the playerglobal.swc. Therefore it can't find the 16.0 version.

I suggest you add the following to your build, so that it will use player version 17.0:

    playerVersion = "17.0"
    additionalCompilerOptions = [
            '-target-player=17.0'
    ]

**Comment by aruis** [comment]
I use your suggestions,and now error log show: 'cannot find class flash.filesystem.File' like before.
So ,I think it should not error caused sdk files.
The project url is https://github.com/aruis/stagewebviewbridge.git ，it can reappear the issue.

**Comment by SlevinBE** [comment]
Found the issue. Turned out that the flex-config.xml was used for the configuration of a swcAir project using Flex, which is incorrect since it should be using air-config.xml. This was the reason you got the "cannot find class flash.filesystem.File" error.

I've fixed this issue with commit https://github.com/GradleFx/GradleFx/commit/b8fc8bf1e7d06686dc74511fe45e620ee8dd39dd
A snapshot release is now available on our snapshot repo as version 1.2.1-SNAPSHOT

**Comment by vaukalak** [comment]
@SlevinBE 

"Turned out that the flex-config.xml was used for the configuration of a swcAir project using Flex, which is incorrect since it should be using air-config.xml."

actually seems, that it uses it also for swc. so, is I use airsdk version 18.0, it will be impossible to build (it doesn't have frameworks/flex-config.xml, it has only airsdk.xml).

**Comment by SlevinBE** [comment]
If I remember correctly then you are using the AIR SDK without the Flex SDK. In that case you have to use the default AIR SDK provided by Adobe (AIRSDK_Compiler), not the one for Flex users (AdobeAIRSDK): http://www.adobe.com/devnet/air/air-sdk-download.html

The AIR SDK for Flex does indeed not have the *-config.xml files in it, because it assumes they are provided by the Flex SDK. The non-Flex AIR SDK has those files in them.

**Comment by aruis** [comment]
Thank you @SlevinBE . It works in 1.2.1-SNAPSHOT.
